### ISSUE TITLE
Importing other .py files

### ISSUE THREAD

**Issue by krambriw** [arnauorriols/node-red-contrib-python-function#3]
This is a cool node, been looking for something like this,

Running Node-RED on a RPi. Do you know "how to" or where to put additional .py files to import into the node. Like mosquitto.py

Currently the following fails

import mosquitto.py
with error
Traceback (most recent call last): File "<string>", line 101, in <module> File "<string>", line 59, in python_function ImportError: No module named mosquitto.py

as well as

import /home/pi/mosquitto.py
with error
File "<string>", line 60 import /home/pi/mosquitto.py ^ SyntaxError: invalid syntax

**Comment by sorscode** [comment]
Two years old, but I'll respond

`import sys`
`sys.path.append('/path/to/your/module')`
`import custom_module`
